### ISSUE TITLE
What's the reasoning behind this scummy behavior?

### ISSUE THREAD

**Issue by Coolsonickirby** [xNaxdy/latency-slider-de#1]
Quite frankly, I'm wondering why you decided to modify and upload another person's work without their consent and directly going against their wishes. Is it because of that $50 bounty on twitter? Or because you want people to have an easy way of cheating? Being able to reduce the latency for QP and hiding the text certainly seems to prove that you're fine with being scummy and trying to encourage cheating.

**Comment by xNaxdy** [comment]
Thanks for the question. The original author gave their consent when they decided to publish their source code under the AGPL license, which gives everyone the right to modify and publish modified versions of the software so long as the license is preserved (even if the original repo is privatized).

As for the rest, I'm of the opinion that everyone should be free to choose how they use their software. Personally, I find the limitations of the latest original to be unnecessary and overbearing, hence I created a version with any and all limits removed.
