### ISSUE TITLE
Kicked from arena mid-game

### ISSUE THREAD

**Issue by avahe-kellenberger** [xNaxdy/latency-slider-de#20]
Attempting to see if the ARCropolis crash was fixed after your fix for #19, I was kicked from an arena very shortly after the match had started (maybe 5 or 10 seconds).

I wasn't actually playing this game, but spectating while I was next in line to play.
Have you tested the fix yourself, or have you ever been kicked from an arena?

Thanks.

**Comment by xNaxdy** [comment]
I've tested the fix with and without stealth mode and have had no issues. Sure the host didn't boot you for not actually playing?

**Comment by avahe-kellenberger** [comment]
Played a bit in a couple different arenas and it didn't happen again, so maybe you were right, it was just unfortunate timing lol. I'll close this for now unless I start seeing it happening again, and consistently.
