### ISSUE TITLE
13.0.3 Update

### ISSUE THREAD

**Issue by camrentm** [xNaxdy/latency-slider-de#28]
I'm sure you already know, but there was a new update to Smash Ultimate. Not sure if it breaks the mod just yet however, since Arcropolis won't boot without an update

**Comment by Naxdy** [comment]
It'll most likely break, but dw I will look to update asap.

**Comment by Naxdy** [comment]
Progress is currently pending https://github.com/Atmosphere-NX/Atmosphere/pull/2387 since I need to update my Switch first before it'll let me update Smash, but without atmosphere updated as well, I won't be able to test my changes.
